# Basic Information 
title: Aymen Mir
position: Ph.D. Student
affiliation: University of Tübingen, Max Planck Institute for Informatics
affiliation_link: https://virtualhumans.mpi-inf.mpg.de/
email: aymenmir13@gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Computer Vision, Computer Graphics, Virtual Humans, Human Pose Estimation, Gaussian Splatting, Motion Synthesis
description: Ph.D. student at the University of Tübingen and the Max Planck Institute for Informatics, working on the capture and synthesis of realistic virtual humans.
canonical: https://miraymen.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=Sjnv-1cAAAAJ&hl=en
github_link: https://github.com/miraymen
youtube: https://www.youtube.com/@aymenmir
linkedin: https://www.linkedin.com/in/aymen-mir-6b68882a4
# twitter: https://x.com/aymenmmir
cv_link: assets/files/mir_resume.pdf

# Images (profile picture and favicon)
avatar: ./assets/img/image.jpg
favicon: ./assets/img/favicon.png

# Google Analytics (GA4) Measurement ID
google_analytics: G-BXH2966VL8

# All editable content (bio, publications data + template) lives in one folder.
includes_dir: _content
data_dir: _content

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
